name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: olafurpg/setup-scala@v10
    - uses: actions/setup-node@v1
    - name: Compile 2.12.13
      run: sbt -J-Xmx3000m clean test docs/mdoc coreJVM/mimaReportBinaryIssues linalg/mimaReportBinaryIssues 
    - name: Test coverage 2.12.12
      run: sbt -J-Xmx3000m clean coverage "++2.12.12 testJVM" coverageAggregate
    - name: Codecov
      uses: codecov/codecov-action@v1.0.2
      if: github.actor == 'pityka'
      with:
        token: ${{secrets.CODECOV_TOKEN}}

