name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
      distribution: temurin
      java-version: 8
    - uses: actions/setup-node@v1
    - name: Compile 2.13
      run: sbt -J-Xmx3000m clean test docs/mdoc coreJVM/mimaReportBinaryIssues linalg/mimaReportBinaryIssues 
    - name: Compile 2.12
      run: sbt -J-Xmx3000m ++2.12.13! clean test docs/mdoc coreJVM/mimaReportBinaryIssues linalg/mimaReportBinaryIssues 
