name: sonatype
on:
  push:
    branches: [master]
    tags: ["*"]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          submodules: recursive
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 8
      - uses: actions/setup-node@v1
      - uses: olafurpg/setup-gpg@v3
      - uses: peaceiris/actions-hugo@v2.4.13
        with: 
          hugo-version: '0.89.4'
          extended: true
      - name: Publish
        run: |
          git ls-remote --get-url origin
          sbt -J-Xmx3000m test versionCheck ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      - name: website
        run: |
          sbt clean docs/mdoc docs/unidoc
          cd website
          hugo
          cd public
          touch .nojekyll
      - name: gh-pages-deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./website/public
          